# Generated by Django 5.0.1 on 2025-01-20 00:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_rename_user_chorematesuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompleteChores",
        ),
        migrations.RemoveField(
            model_name="chorematesuser",
            name="name",
        ),
        migrations.AddField(
            model_name="chore",
            name="completedStatus",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chorematesuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chorematesuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chorematesuser",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chorematesuser",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="database.household",
            ),
        ),
        migrations.AlterField(
            model_name="chorematesuser",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.RunSQL(
    """
    DROP VIEW complete_chores
    """,
        ),
    ]
